# COGS 108 - Data Checkpoint

# Names

- Anh Vuong
- Anh Bach
- Anh Pham
- Huy Nguyen

<a id='research_question'></a>
# Research Question

* How have housing costs (rent and owner-occupied) in California (based on cities) change over time from 2020 to 2021, and how does this compare to Texas?
* What percentage of of a household income is typically spent on housing in California from 2020 to 2021, and how does this compare to Texas?
* What has been the population rate of California over time, and how has it changed from 2020 to 2021? 
* Does increase in housing costs affect the decreasing in California's populations from 2020 to 2021?

# Background and Prior Work

It is widely acknowledged that California is the most populated state in the United States, with nearly 40 million residents, but only the third largest state. As a result, there is a conflict between the population and area in California, thus leading to the increasing trend in housing prices in recent years. In fact, the socioeconomic makeup of a region is significantly influenced by housing costs and population trends. This project intends to examine historical housing cost increases in California, compare them to those in other states, and comprehend any prospective effects on the state's population.

As all members of our group are California residents and are renting a place to live off-campus, we can feel the pressure while paying the rent. Especially after the emergence of the COVID-19 pandemic, there was an increasing trend in housing prices in California, and some news reports reported that more Californians were moving out of state due to the housing situation. Hence, we are interested in determining the relationship between the increasing cost of housing and California’s population.

To dig into the question, we conducted some research to explore the housing situation in California following the emergence of COVID-19. According to a report from John Duca and Anthony Murphy, in the wake of the short but steep COVID-19 recession, house prices have risen at record levels in recent months, hitting a peak increase of 19.3 percent in July 2021. These double-digit increases represent a stark departure from what occurred before the pandemic—from early 2013 to early 2020—when house prices rose at a moderate annual rate of about 5 percent and exceeded the rate of increase in rents (1). Then, we do some research to get a good understanding of the housing market in California compared to other states in the U.S. An analysis by Jack Caporal and Lyle Daly pointed out that the typical home price in California is $728,000, which is 218% of the typical U.S. price, and that California has the second highest typical home value in the United States and the second lowest income-to-home-value ratio, despite residents making 22% more than the median U.S. income (2). Lastly, we look at the California population trend in recent years. A report from Calmatters stated that according to the latest population estimates from the U.S. Census Bureau, California’s total population declined by more than 500,000 between April 2020 and July 2022. Put another way, 1 out of 100 people living in California at the beginning of the COVID-19 pandemic had, two years later, left the state — either by U-Haul or by hearse (3).

References (include links):

1. https://www.dallasfed.org/research/economics/2021/1228

2. https://www.fool.com/the-ascent/research/average-house-price-state/

3. https://calmatters.org/newsletters/whatmatters/2023/02/california-population-exodus-housing/

# Hypothesis

Our group hypothesis is that there is a relationship between the decrease in California's populations and the increase in cost of spending on housing (rent and owner-occupied) from 2020 to 2021 in which California residents are likely to move out of state because they are not able to afford housing. 

H<sub>0</sub>: There is no relationship between increasing in cost of housing in California and the decreasing in California's populations from 2020 to 2021.

H<sub>1</sub>: There is a relationship between increasing in cost of housing in California and the decreasing in California's populations from 2020 to 2021.

# Ethics & Privacy

In order to address ethics and privacy concerns, our group focused on using datasets that are publicly available online and our project is mainly for academic purposes. Our datasets are collected from government websites without sensitive or personally identifying information. We believe that our datasets are unbiased and ethical because we mainly focus on analyzing data on California’s populations and housing costs and comparing them to other states to see if there possibly is a relationship between housing costs and populations without focusing on any human bias. Our group makes sure there is no bias by aiming to collect and analyze publicly available data and datasets from trusted websites for our project and our datasets do not exclude any particular populations or are likely to reflect particular human biases in a way that could be a problem. Our datasets also do not target any particular group or conduct in a way that will lead to a particular group, whether that's defined by sex, age, ethnicity, etc. 

To detect any biases before our analysis, we will examine the source and methodology of the data collection, and check if there are any gaps or inconsistencies in the data. We will also review the literature on the topic and compare our data with other relevant studies. During our analysis, we will use appropriate statistical methods and visualizations to explore the data and identify any outliers, trends, or patterns that may indicate bias. We will also test our hypotheses and assumptions using inferential statistics and hypothesis testing. After our analysis, we will evaluate our results and conclusions in light of the data limitations and ethical implications. We will also seek feedback from our peers and instructors on our project report and presentation, and address any questions or concerns they may have. 

To handle any issues we identified, we will document them clearly and transparently in our project report and presentation, and acknowledge the limitations and uncertainties of our analysis. We will also suggest ways to improve the data quality and reliability in future research and discuss the potential implications and recommendations for policy and practice based on our findings.

# Dataset(s)

- Dataset Name: Rentals  
- Link to the dataset: https://files.zillowstatic.com/research/public_csvs/zori/City_zori_sm_month.csv?t=1684286197
- Number of observations: 3058

The Rentals dataset is found on Zillow. The dataset contains different regions in the U.S, rental prices dates, and states. 

- Dataset Name: Home Values  
- Link to the dataset: https://files.zillowstatic.com/research/public_csvs/zhvi/City_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv?t=1684286197
- Number of observations: 22258

The Home Values dataset is found on Zillow. The dataset contains home values (including houses, single-family residential homes, condos, and cooperative housing) for different regions in the U.S., dates, and states.

- Dataset Name: Financial Characteristics
- Link to the dataset:  
https://data.census.gov/table?q=state+housing+cost&tid=ACSST5Y2020.S2503  
https://data.census.gov/table?q=state+housing+cost&tid=ACSST5Y2021.S2503
- Number of observations: 49

The Financial Characteristics dataset is found on the U.S. Census Bureau website. The dataset contains the Household Income in the past 12 months (In 2020 and 2-2021 inflation-adjusted dollars) and the Monthly Housing Costs in both 2020 and 2021 for all 50 states in the U.S. including District of Columbia and Puerto Rico.  

- Dataset Name: U.S. Populations
- Link to the dataset:  
https://www2.census.gov/programs-surveys/popest/datasets/2020-2022/state/totals/
- Number of observations: 66

The U.S. Population dataset is found on the U.S. Census Bureau website. The dataset contains estimated populations for all regions in the United States from 2020 to 2022 including birth rate, death rate, international immigration, and domestic immigration
  
Our analysis involves four interconnected datasets: California and Texas populations, housing prices (rentals and home values), and the amount of residents' income spent on housing. By examining these datasets, we aim to uncover trends in population growth or decline as well as changes in housing costs (both rentals and home values) from 2020 to 2021 in both states. Furthermore, we will investigate whether there is a burden on residents in terms of housing expenses and explore if this factor contributes to the migration of California residents to other states.

# Setup

In [56]:
# import working with data libraries
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None 
pd.set_option('display.float_format', '{:.2f}'.format)

# import visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [57]:
# Set auto format on all cells
%autosave 0

Autosave disabled

### Rentals

In [58]:
rentals = pd.read_csv('data/Cities_rent_prices.csv')
rentals.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2015-03-31,2015-04-30,...,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2713.60,2739.39,...,3502.84,3533.91,3532.30,3507.20,3462.29,3428.61,3417.70,3431.30,3457.78,3499.71
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,1956.88,1965.96,...,2879.22,2894.26,2908.89,2901.41,2892.76,2884.37,2882.66,2884.80,2890.98,2902.22
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,1277.77,1283.62,...,1594.23,1601.71,1601.11,1596.78,1589.47,1585.43,1591.96,1601.85,1611.70,1616.97
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,1586.58,1601.00,...,2002.34,2009.10,2008.05,2002.81,1994.91,1995.00,2001.11,2017.67,2035.22,2055.12
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,1026.43,1034.26,...,1476.50,1480.10,1478.38,1468.80,1465.44,1460.62,1464.34,1461.77,1471.29,1472.29

### Home Values

In [59]:
home_values = pd.read_csv('data/Home_values.csv')
home_values.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2000-01-31,2000-02-29,...,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,131748.38,132455.15,...,651406.91,652566.15,649451.98,647042.56,644116.65,639562.42,636574.80,636522.38,640865.68,648402.40
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,215492.29,215796.93,...,958752.17,956301.04,951672.56,946636.08,944122.95,940643.45,931859.83,918976.83,907602.72,901961.10
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,98322.10,98295.78,...,265763.78,266867.32,267073.58,267042.88,267029.70,266274.68,264819.96,263256.31,262531.09,262337.29
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,121417.33,121451.26,...,285802.83,283550.66,280876.67,278762.11,277787.20,276777.00,277879.30,279127.25,280811.96,281258.73
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,97194.62,97285.79,...,266901.69,267741.24,267389.56,266847.73,266298.89,265154.99,264000.20,263038.48,263217.00,263230.89

### Financial Characteristics

In [60]:
# 2020 dataset
df2020 = pd.read_csv('data/ACSST5Y2020.S2503-2023-05-17T062125.csv')
df2020.head()

,Label (Grouping),Alabama!!Occupied housing units!!Estimate,Alabama!!Percent occupied housing units!!Estimate,Alabama!!Owner-occupied housing units!!Estimate,Alabama!!Percent owner-occupied housing units!!Estimate,Alabama!!Renter-occupied housing units!!Estimate,Alabama!!Percent renter-occupied housing units!!Estimate,Alaska!!Occupied housing units!!Estimate,Alaska!!Percent occupied housing units!!Estimate,Alaska!!Owner-occupied housing units!!Estimate,...,Wyoming!!Owner-occupied housing units!!Estimate,Wyoming!!Percent owner-occupied housing units!!Estimate,Wyoming!!Renter-occupied housing units!!Estimate,Wyoming!!Percent renter-occupied housing units!!Estimate,Puerto Rico!!Occupied housing units!!Estimate,Puerto Rico!!Percent occupied housing units!!Estimate,Puerto Rico!!Owner-occupied housing units!!Estimate,Puerto Rico!!Percent owner-occupied housing units!!Estimate,Puerto Rico!!Renter-occupied housing units!!Estimate,Puerto Rico!!Percent renter-occupied housing units!!Estimate
0,Occupied housing units,"1,888,504","1,888,504","1,306,505","1,306,505","581,999","581,999","255,173","255,173","165,376",...,"165,530","165,530","67,701","67,701","1,205,749","1,205,749","817,399","817,399","388,350","388,350"
1,HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Less than $5,000","77,186",4.1%,"31,936",2.4%,"45,250",7.8%,"5,949",2.3%,"2,800",...,"3,088",1.9%,"2,982",4.4%,"178,920",14.8%,"70,259",8.6%,"108,661",28.0%
3,"$5,000 to $9,999","76,449",4.0%,"28,772",2.2%,"47,677",8.2%,"3,869",1.5%,"1,735",...,"2,413",1.5%,"3,580",5.3%,"139,250",11.5%,"78,136",9.6%,"61,114",15.7%
4,"$10,000 to $14,999","105,415",5.6%,"50,340",3.9%,"55,075",9.5%,"7,476",2.9%,"3,020",...,"3,775",2.3%,"4,927",7.3%,"140,728",11.7%,"91,381",11.2%,"49,347",12.7%

In [62]:
# 2021 dataset
df2021 = pd.read_csv('data/ACSST5Y2021.S2503-2023-05-17T062108.csv')
df2021.head()

,Label (Grouping),Alabama!!Occupied housing units!!Estimate,Alabama!!Percent occupied housing units!!Estimate,Alabama!!Owner-occupied housing units!!Estimate,Alabama!!Percent owner-occupied housing units!!Estimate,Alabama!!Renter-occupied housing units!!Estimate,Alabama!!Percent renter-occupied housing units!!Estimate,Alaska!!Occupied housing units!!Estimate,Alaska!!Percent occupied housing units!!Estimate,Alaska!!Owner-occupied housing units!!Estimate,...,Wyoming!!Owner-occupied housing units!!Estimate,Wyoming!!Percent owner-occupied housing units!!Estimate,Wyoming!!Renter-occupied housing units!!Estimate,Wyoming!!Percent renter-occupied housing units!!Estimate,Puerto Rico!!Occupied housing units!!Estimate,Puerto Rico!!Percent occupied housing units!!Estimate,Puerto Rico!!Owner-occupied housing units!!Estimate,Puerto Rico!!Percent owner-occupied housing units!!Estimate,Puerto Rico!!Renter-occupied housing units!!Estimate,Puerto Rico!!Percent renter-occupied housing units!!Estimate
0,Occupied housing units,"1,902,983","1,902,983","1,320,571","1,320,571","582,412","582,412","260,561","260,561","171,207",...,"165,359","165,359","65,294","65,294","1,196,790","1,196,790","814,154","814,154","382,636","382,636"
1,HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Less than $5,000","75,815",4.0%,"32,168",2.4%,"43,647",7.5%,"6,479",2.5%,"2,955",...,"3,126",1.9%,"2,923",4.5%,"168,882",14.1%,"65,579",8.1%,"103,303",27.0%
3,"$5,000 to $9,999","64,390",3.4%,"24,291",1.8%,"40,099",6.9%,"4,165",1.6%,"1,823",...,"2,144",1.3%,"3,364",5.2%,"130,319",10.9%,"73,900",9.1%,"56,419",14.7%
4,"$10,000 to $14,999","103,832",5.5%,"47,049",3.6%,"56,783",9.7%,"7,170",2.8%,"2,984",...,"3,700",2.2%,"4,823",7.4%,"137,111",11.5%,"88,834",10.9%,"48,277",12.6%

### Population

In [63]:
df_pop_est = pd.read_csv('./data/NST-EST2022-ALLDATA.csv')
df_pop_est.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,NPOPCHG_2020,...,RDEATH2021,RDEATH2022,RNATURALCHG2021,RNATURALCHG2022,RINTERNATIONALMIG2021,RINTERNATIONALMIG2022,RDOMESTICMIG2021,RDOMESTICMIG2022,RNETMIG2021,RNETMIG2022
0,10,0,0,0,United States,331449520,331511512,332031554,333287557,61992,...,10.36,10.35,0.43,0.74,1.13,3.04,0.00,0.00,1.13,3.04
1,20,1,0,0,Northeast Region,57609156,57448898,57259257,57040406,-160258,...,9.78,9.87,0.21,0.51,1.40,3.75,-4.86,-8.06,-3.45,-4.31
2,30,1,1,0,New England,15116206,15074473,15121745,15129548,-41733,...,9.53,9.89,-0.31,-0.21,1.77,4.66,1.55,-3.77,3.32,0.89
3,30,1,2,0,Middle Atlantic,42492950,42374425,42137512,41910858,-118525,...,9.87,9.86,0.39,0.77,1.27,3.43,-7.14,-9.61,-5.87,-6.18
4,20,2,0,0,Midwest Region,68985537,68961043,68836505,68787595,-24494,...,11.06,11.17,-0.21,-0.13,0.80,2.11,-2.65,-2.53,-1.84,-0.42

# Data Cleaning

### Cleaning Rentals and Home Values

First, we only keep the columns that are necessary for our analysis in both Home Values and Rentals datasets. Therefore, we will remove unnecessary and duplicated columns such as RegionID, SizeRank, RegionType, Metro, StateName.

In [64]:
rentals_df = rentals.drop(columns = ['RegionID', 'SizeRank', 'RegionType', 'StateName', 'Metro'])
rentals_df.head()

,RegionName,State,CountyName,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,...,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30
0,New York,NY,Queens County,2713.60,2739.39,2762.87,2785.53,2800.16,2814.59,2826.08,...,3502.84,3533.91,3532.30,3507.20,3462.29,3428.61,3417.70,3431.30,3457.78,3499.71
1,Los Angeles,CA,Los Angeles County,1956.88,1965.96,1983.06,1996.93,2018.20,2035.56,2054.40,...,2879.22,2894.26,2908.89,2901.41,2892.76,2884.37,2882.66,2884.80,2890.98,2902.22
2,Houston,TX,Harris County,1277.77,1283.62,1293.96,1306.04,1311.23,1317.00,1313.47,...,1594.23,1601.71,1601.11,1596.78,1589.47,1585.43,1591.96,1601.85,1611.70,1616.97
3,Chicago,IL,Cook County,1586.58,1601.00,1616.00,1626.78,1635.25,1640.22,1640.08,...,2002.34,2009.10,2008.05,2002.81,1994.91,1995.00,2001.11,2017.67,2035.22,2055.12
4,San Antonio,TX,Bexar County,1026.43,1034.26,1044.44,1051.87,1055.72,1054.79,1052.94,...,1476.50,1480.10,1478.38,1468.80,1465.44,1460.62,1464.34,1461.77,1471.29,1472.29

In [65]:
home_values_df = home_values.drop(columns = ['RegionID', 'SizeRank', 'RegionType', 'StateName', 'Metro'])
home_values_df.head()

,RegionName,State,CountyName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,...,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30
0,New York,NY,Queens County,131748.38,132455.15,133172.63,134560.11,135952.72,137452.07,139023.21,...,651406.91,652566.15,649451.98,647042.56,644116.65,639562.42,636574.80,636522.38,640865.68,648402.40
1,Los Angeles,CA,Los Angeles County,215492.29,215796.93,216730.58,218588.29,220924.23,223189.63,225514.65,...,958752.17,956301.04,951672.56,946636.08,944122.95,940643.45,931859.83,918976.83,907602.72,901961.10
2,Houston,TX,Harris County,98322.10,98295.78,98159.00,98115.04,98097.22,98260.88,98465.22,...,265763.78,266867.32,267073.58,267042.88,267029.70,266274.68,264819.96,263256.31,262531.09,262337.29
3,Chicago,IL,Cook County,121417.33,121451.26,121760.21,122543.59,123591.28,124725.04,125781.21,...,285802.83,283550.66,280876.67,278762.11,277787.20,276777.00,277879.30,279127.25,280811.96,281258.73
4,San Antonio,TX,Bexar County,97194.62,97285.79,97355.59,97480.82,97032.68,96417.65,95749.36,...,266901.69,267741.24,267389.56,266847.73,266298.89,265154.99,264000.20,263038.48,263217.00,263230.89

Secondly, we only want to keep the data for two states (California and Texas) from 2020 to 2021 in both Home Values and Rentals datasets for futher analysis so we will remove all data that is not from California and Texas and in the range 2020 to 2021.

In [66]:
date_columns = rentals_df.columns[rentals_df.columns.str.match(r'\d{4}-\d{2}-\d{2}')]
under_2020 = [col for col in date_columns if '2015' <= col[:4] < '2020']
above_2021 = [col for col in date_columns if '2022' <= col[:4]]
rentals_df = rentals_df.drop(columns = under_2020)
rentals_df = rentals_df.drop(columns = above_2021)
desired_states = ['CA', 'TX']
rentals_df = rentals_df[rentals_df['State'].isin(desired_states)]
rentals_df.head()

,RegionName,State,CountyName,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,...,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31
1,Los Angeles,CA,Los Angeles County,2510.28,2518.62,2517.04,2500.80,2475.75,2456.68,2450.78,...,2422.79,2438.46,2463.39,2495.74,2539.99,2595.53,2637.64,2668.22,2685.79,2707.70
2,Houston,TX,Harris County,1393.81,1396.58,1398.85,1392.25,1381.54,1370.17,1368.06,...,1373.25,1388.31,1414.68,1446.19,1476.32,1502.31,1513.30,1521.81,1523.82,1531.17
4,San Antonio,TX,Bexar County,1194.69,1199.10,1200.11,1196.88,1194.36,1194.06,1199.38,...,1227.98,1241.48,1261.77,1285.28,1314.39,1349.42,1377.23,1389.72,1390.66,1394.12
8,San Diego,CA,San Diego County,2284.07,2291.36,2299.29,2286.39,2272.85,2265.46,2279.49,...,2366.21,2398.51,2448.29,2495.34,2551.46,2614.24,2678.74,2726.51,2759.68,2772.30
9,Dallas,TX,Dallas County,1384.97,1392.60,1401.31,1399.37,1393.15,1386.81,1385.40,...,1409.04,1430.89,1459.24,1497.13,1536.56,1568.75,1591.49,1599.46,1610.59,1616.32

In [67]:
date_columns = home_values_df.columns[home_values_df.columns.str.match(r'\d{4}-\d{2}-\d{2}')]
under_2020 = [col for col in date_columns if '2000' <= col[:4] < '2020']
above_2021 = [col for col in date_columns if '2022' <= col[:4]]
home_values_df = home_values_df.drop(columns = under_2020)
home_values_df = home_values_df.drop(columns = above_2021)
desired_states = ['CA', 'TX']
home_values_df = home_values_df[home_values_df['State'].isin(desired_states)]
home_values_df.head()

,RegionName,State,CountyName,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,...,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31
1,Los Angeles,CA,Los Angeles County,718764.06,721724.91,723314.01,724390.00,722622.73,718010.76,717494.09,...,801985.93,808613.99,819086.43,832229.17,847534.39,860706.60,872235.27,881017.62,889984.77,899778.21
2,Houston,TX,Harris County,192470.07,193304.53,194095.50,194661.91,194793.17,194865.30,195259.70,...,212538.59,215555.29,218936.54,222528.44,225677.57,227879.47,229380.34,231156.00,233653.48,236598.49
4,San Antonio,TX,Bexar County,191295.67,192483.68,193537.30,194249.51,194590.77,194859.07,195555.95,...,213935.53,216757.46,219858.64,223260.88,226477.76,228939.85,230744.21,232470.05,234943.26,237959.70
8,San Diego,CA,San Diego County,645762.30,649821.29,654802.93,660529.98,663553.88,664411.67,664944.17,...,742320.48,755756.36,771645.30,788159.71,802479.12,810910.50,814848.73,818352.86,824976.14,835340.08
9,Dallas,TX,Dallas County,223110.97,225481.89,227739.70,228695.15,228468.47,227804.86,227776.65,...,253019.53,257051.43,260825.87,264337.46,267366.64,269532.27,271337.46,273289.33,276098.17,279462.22

Then, we want to create two different tables (rentals and home values) for California and Texas separately and sort the tables in decreasing order for futher analysis.

In [68]:
CA_rentals = rentals_df[rentals_df['State'] == 'CA']
date_columns = CA_rentals.columns[CA_rentals.columns.str.match(r'\d{4}-\d{2}-\d{2}')]

year_2020 = [col for col in date_columns if col[:4] == '2020']
CA_rentals['2020 Rentals'] = CA_rentals[year_2020].mean(axis=1, skipna=True)
year_2021 = [col for col in date_columns if col[:4] == '2021']
CA_rentals['2021 Rentals'] = CA_rentals[year_2021].mean(axis=1, skipna= True)

CA_rentals_df = CA_rentals[['RegionName', 'State', 'CountyName', '2020 Rentals', '2021 Rentals']]
years = ['2020 Rentals', '2021 Rentals']
CA_rentals_df = CA_rentals_df.sort_values(by= years, ascending=False)

CA_rentals_df.head()

           RegionName State          CountyName  2020 Rentals  2021 Rentals
2487           Malibu    CA  Los Angeles County      10146.77      12119.09
2365         Coronado    CA    San Diego County       4515.23       5062.86
1621  Manhattan Beach    CA  Los Angeles County       4500.53       4735.68
779         Palo Alto    CA  Santa Clara County       4049.45       3946.45
2374     Laguna Beach    CA       Orange County       4024.19       4598.19

In [69]:
CA_home_values = home_values_df[home_values_df['State'] == 'CA']
date_columns = CA_home_values.columns[CA_home_values.columns.str.match(r'\d{4}-\d{2}-\d{2}')]

year_2020 = [col for col in date_columns if col[:4] == '2020']
CA_home_values['2020 Home Values'] = CA_home_values[year_2020].mean(axis=1, skipna=True)
year_2021 = [col for col in date_columns if col[:4] == '2021']
CA_home_values['2021 Home Values'] = CA_home_values[year_2021].mean(axis=1, skipna= True)

CA_home_values_df = CA_home_values[['RegionName', 'State', 'CountyName', '2020 Home Values', '2021 Home Values']]
years = ['2020 Home Values', '2021 Home Values']
CA_home_values_df = CA_home_values_df.sort_values(by= years, ascending=False)

CA_home_values_df.head()

,RegionName,State,CountyName,2020 Home Values,2021 Home Values
6506,Atherton,CA,San Mateo County,6082732.22,6940974.87
6163,Los Altos Hills,CA,Santa Clara County,4309094.15,4855607.99
4918,Hillsborough,CA,San Mateo County,4141242.17,4745918.94
12534,Belvedere,CA,Marin County,3557472.75,4110908.36
14910,Hidden Hills,CA,Los Angeles County,3533298.64,4170815.07

In [70]:
CA_housings = pd.merge(CA_rentals_df, CA_home_values_df, on=['RegionName', 'State', 'CountyName'], how='inner')
CA_housings.head()

,RegionName,State,CountyName,2020 Rentals,2021 Rentals,2020 Home Values,2021 Home Values
0,Malibu,CA,Los Angeles County,10146.77,12119.09,2397464.18,2986831.75
1,Coronado,CA,San Diego County,4515.23,5062.86,1695783.52,1958157.17
2,Manhattan Beach,CA,Los Angeles County,4500.53,4735.68,2262795.39,2587550.28
3,Palo Alto,CA,Santa Clara County,4049.45,3946.45,2807007.97,3079778.66
4,Laguna Beach,CA,Orange County,4024.19,4598.19,1943903.55,2301971.24

In [71]:
TX_rentals = rentals_df[rentals_df['State'] == 'TX']
date_columns = TX_rentals.columns[TX_rentals.columns.str.match(r'\d{4}-\d{2}-\d{2}')]

year_2020 = [col for col in date_columns if col[:4] == '2020']
TX_rentals['2020 Rentals'] = TX_rentals[year_2020].mean(axis=1, skipna=True)
year_2021 = [col for col in date_columns if col[:4] == '2021']
TX_rentals['2021 Rentals'] = TX_rentals[year_2021].mean(axis=1, skipna= True)

TX_rentals_df = TX_rentals[['RegionName', 'State', 'CountyName', '2020 Rentals', '2021 Rentals']]
years = ['2020 Rentals', '2021 Rentals']
TX_rentals_df = TX_rentals_df.sort_values(by= years, ascending=False)

TX_rentals_df.head()

         RegionName State        CountyName  2020 Rentals  2021 Rentals
1465     Midlothian    TX      Ellis County       1895.13       2116.69
2835       Bee Cave    TX     Travis County       1791.47       2076.95
701    Flower Mound    TX     Denton County       1737.85       1928.41
844      Little Elm    TX     Denton County       1721.88       1999.27
419   Missouri City    TX  Fort Bend County       1698.06       1845.31

In [72]:
TX_home_values = home_values_df[home_values_df['State'] == 'TX']
date_columns = TX_home_values.columns[TX_home_values.columns.str.match(r'\d{4}-\d{2}-\d{2}')]

year_2020 = [col for col in date_columns if col[:4] == '2020']
TX_home_values['2020 Home Values'] = TX_home_values[year_2020].mean(axis=1, skipna=True)
year_2021 = [col for col in date_columns if col[:4] == '2021']
TX_home_values['2021 Home Values'] = TX_home_values[year_2021].mean(axis=1, skipna= True)

TX_home_values_df = TX_home_values[['RegionName', 'State', 'CountyName', '2020 Home Values', '2021 Home Values']]
years = ['2020 Home Values', '2021 Home Values']
TX_home_values_df = TX_home_values_df.sort_values(by= years, ascending=False)

TX_home_values_df.head()

,RegionName,State,CountyName,2020 Home Values,2021 Home Values
15352,Westover Hills,TX,Tarrant County,1596170.15,1807368.69
14761,Rollingwood,TX,Travis County,1594811.21,1964007.84
5818,Highland Park,TX,Dallas County,1556576.77,1829795.60
9922,West Lake Hills,TX,Travis County,1388718.36,1762152.93
2471,University Park,TX,Dallas County,1369360.37,1561514.78

In [73]:
TX_housings = pd.merge(TX_rentals_df, TX_home_values_df, on=['RegionName', 'State', 'CountyName'], how='inner')
TX_housings.head()

,RegionName,State,CountyName,2020 Rentals,2021 Rentals,2020 Home Values,2021 Home Values
0,Midlothian,TX,Ellis County,1895.13,2116.69,324437.84,375673.46
1,Bee Cave,TX,Travis County,1791.47,2076.95,634045.23,801295.49
2,Flower Mound,TX,Denton County,1737.85,1928.41,469449.36,520467.59
3,Little Elm,TX,Denton County,1721.88,1999.27,327963.17,372731.03
4,Missouri City,TX,Fort Bend County,1698.06,1845.31,267954.83,300671.12

### Cleaning Financial Characteristics Datasets

Firstly, we need to separate each of our 2020 and 2021 datasets into two different tables of Household Income and Housing Cost and remove rows where all the columns have missing data for that participant in 4 tables.

In [74]:
household_income_2020 = df2020.loc[1:13]
household_income_2020 = household_income_2020.dropna()
household_income_2020.head()

,Label (Grouping),Alabama!!Occupied housing units!!Estimate,Alabama!!Percent occupied housing units!!Estimate,Alabama!!Owner-occupied housing units!!Estimate,Alabama!!Percent owner-occupied housing units!!Estimate,Alabama!!Renter-occupied housing units!!Estimate,Alabama!!Percent renter-occupied housing units!!Estimate,Alaska!!Occupied housing units!!Estimate,Alaska!!Percent occupied housing units!!Estimate,Alaska!!Owner-occupied housing units!!Estimate,...,Wyoming!!Owner-occupied housing units!!Estimate,Wyoming!!Percent owner-occupied housing units!!Estimate,Wyoming!!Renter-occupied housing units!!Estimate,Wyoming!!Percent renter-occupied housing units!!Estimate,Puerto Rico!!Occupied housing units!!Estimate,Puerto Rico!!Percent occupied housing units!!Estimate,Puerto Rico!!Owner-occupied housing units!!Estimate,Puerto Rico!!Percent owner-occupied housing units!!Estimate,Puerto Rico!!Renter-occupied housing units!!Estimate,Puerto Rico!!Percent renter-occupied housing units!!Estimate
2,"Less than $5,000","77,186",4.1%,"31,936",2.4%,"45,250",7.8%,"5,949",2.3%,"2,800",...,"3,088",1.9%,"2,982",4.4%,"178,920",14.8%,"70,259",8.6%,"108,661",28.0%
3,"$5,000 to $9,999","76,449",4.0%,"28,772",2.2%,"47,677",8.2%,"3,869",1.5%,"1,735",...,"2,413",1.5%,"3,580",5.3%,"139,250",11.5%,"78,136",9.6%,"61,114",15.7%
4,"$10,000 to $14,999","105,415",5.6%,"50,340",3.9%,"55,075",9.5%,"7,476",2.9%,"3,020",...,"3,775",2.3%,"4,927",7.3%,"140,728",11.7%,"91,381",11.2%,"49,347",12.7%
5,"$15,000 to $19,999","106,327",5.6%,"54,698",4.2%,"51,629",8.9%,"8,007",3.1%,"3,623",...,"4,603",2.8%,"5,040",7.4%,"122,435",10.2%,"80,281",9.8%,"42,154",10.9%
6,"$20,000 to $24,999","100,073",5.3%,"55,652",4.3%,"44,421",7.6%,"7,832",3.1%,"3,511",...,"4,569",2.8%,"4,668",6.9%,"98,371",8.2%,"71,287",8.7%,"27,084",7.0%

In [75]:
housing_costs_2020 = df2020.loc[14:25]
housing_costs_2020 = housing_costs_2020.dropna()
housing_costs_2020.head()

,Label (Grouping),Alabama!!Occupied housing units!!Estimate,Alabama!!Percent occupied housing units!!Estimate,Alabama!!Owner-occupied housing units!!Estimate,Alabama!!Percent owner-occupied housing units!!Estimate,Alabama!!Renter-occupied housing units!!Estimate,Alabama!!Percent renter-occupied housing units!!Estimate,Alaska!!Occupied housing units!!Estimate,Alaska!!Percent occupied housing units!!Estimate,Alaska!!Owner-occupied housing units!!Estimate,...,Wyoming!!Owner-occupied housing units!!Estimate,Wyoming!!Percent owner-occupied housing units!!Estimate,Wyoming!!Renter-occupied housing units!!Estimate,Wyoming!!Percent renter-occupied housing units!!Estimate,Puerto Rico!!Occupied housing units!!Estimate,Puerto Rico!!Percent occupied housing units!!Estimate,Puerto Rico!!Owner-occupied housing units!!Estimate,Puerto Rico!!Percent owner-occupied housing units!!Estimate,Puerto Rico!!Renter-occupied housing units!!Estimate,Puerto Rico!!Percent renter-occupied housing units!!Estimate
15,Less than $300,"220,476",11.7%,"192,456",14.7%,"28,020",4.8%,"11,320",4.4%,"10,102",...,"14,327",8.7%,"2,749",4.1%,"493,118",40.9%,"439,938",53.8%,"53,180",13.7%
16,$300 to $499,"320,897",17.0%,"266,729",20.4%,"54,168",9.3%,"19,094",7.5%,"15,295",...,"31,434",19.0%,"4,621",6.8%,"140,916",11.7%,"71,179",8.7%,"69,737",18.0%
17,$500 to $799,"387,135",20.5%,"215,444",16.5%,"171,691",29.5%,"33,030",12.9%,"24,447",...,"24,978",15.1%,"19,569",28.9%,"192,166",15.9%,"118,409",14.5%,"73,757",19.0%
18,$800 to $999,"251,969",13.3%,"138,513",10.6%,"113,456",19.5%,"23,919",9.4%,"11,803",...,"12,317",7.4%,"12,270",18.1%,"88,653",7.4%,"68,505",8.4%,"20,148",5.2%
19,"$1,000 to $1,499","393,335",20.8%,"270,817",20.7%,"122,518",21.1%,"54,870",21.5%,"25,834",...,"35,366",21.4%,"15,313",22.6%,"90,700",7.5%,"77,039",9.4%,"13,661",3.5%

In [76]:
household_income_2021 = df2021.loc[1:13]
household_income_2021 = household_income_2021.dropna()
household_income_2021.head()

,Label (Grouping),Alabama!!Occupied housing units!!Estimate,Alabama!!Percent occupied housing units!!Estimate,Alabama!!Owner-occupied housing units!!Estimate,Alabama!!Percent owner-occupied housing units!!Estimate,Alabama!!Renter-occupied housing units!!Estimate,Alabama!!Percent renter-occupied housing units!!Estimate,Alaska!!Occupied housing units!!Estimate,Alaska!!Percent occupied housing units!!Estimate,Alaska!!Owner-occupied housing units!!Estimate,...,Wyoming!!Owner-occupied housing units!!Estimate,Wyoming!!Percent owner-occupied housing units!!Estimate,Wyoming!!Renter-occupied housing units!!Estimate,Wyoming!!Percent renter-occupied housing units!!Estimate,Puerto Rico!!Occupied housing units!!Estimate,Puerto Rico!!Percent occupied housing units!!Estimate,Puerto Rico!!Owner-occupied housing units!!Estimate,Puerto Rico!!Percent owner-occupied housing units!!Estimate,Puerto Rico!!Renter-occupied housing units!!Estimate,Puerto Rico!!Percent renter-occupied housing units!!Estimate
2,"Less than $5,000","75,815",4.0%,"32,168",2.4%,"43,647",7.5%,"6,479",2.5%,"2,955",...,"3,126",1.9%,"2,923",4.5%,"168,882",14.1%,"65,579",8.1%,"103,303",27.0%
3,"$5,000 to $9,999","64,390",3.4%,"24,291",1.8%,"40,099",6.9%,"4,165",1.6%,"1,823",...,"2,144",1.3%,"3,364",5.2%,"130,319",10.9%,"73,900",9.1%,"56,419",14.7%
4,"$10,000 to $14,999","103,832",5.5%,"47,049",3.6%,"56,783",9.7%,"7,170",2.8%,"2,984",...,"3,700",2.2%,"4,823",7.4%,"137,111",11.5%,"88,834",10.9%,"48,277",12.6%
5,"$15,000 to $19,999","99,829",5.2%,"53,470",4.0%,"46,359",8.0%,"8,743",3.4%,"4,110",...,"3,906",2.4%,"4,766",7.3%,"121,587",10.2%,"80,465",9.9%,"41,122",10.7%
6,"$20,000 to $24,999","95,400",5.0%,"51,626",3.9%,"43,774",7.5%,"7,393",2.8%,"3,381",...,"4,341",2.6%,"4,538",7.0%,"96,820",8.1%,"68,802",8.5%,"28,018",7.3%

In [77]:
housing_costs_2021 = df2021.loc[14:25]
housing_costs_2021 = housing_costs_2021.dropna()
housing_costs_2021.head()

,Label (Grouping),Alabama!!Occupied housing units!!Estimate,Alabama!!Percent occupied housing units!!Estimate,Alabama!!Owner-occupied housing units!!Estimate,Alabama!!Percent owner-occupied housing units!!Estimate,Alabama!!Renter-occupied housing units!!Estimate,Alabama!!Percent renter-occupied housing units!!Estimate,Alaska!!Occupied housing units!!Estimate,Alaska!!Percent occupied housing units!!Estimate,Alaska!!Owner-occupied housing units!!Estimate,...,Wyoming!!Owner-occupied housing units!!Estimate,Wyoming!!Percent owner-occupied housing units!!Estimate,Wyoming!!Renter-occupied housing units!!Estimate,Wyoming!!Percent renter-occupied housing units!!Estimate,Puerto Rico!!Occupied housing units!!Estimate,Puerto Rico!!Percent occupied housing units!!Estimate,Puerto Rico!!Owner-occupied housing units!!Estimate,Puerto Rico!!Percent owner-occupied housing units!!Estimate,Puerto Rico!!Renter-occupied housing units!!Estimate,Puerto Rico!!Percent renter-occupied housing units!!Estimate
15,Less than $300,"201,670",10.6%,"176,063",13.3%,"25,607",4.4%,"11,165",4.3%,"10,076",...,"12,624",7.6%,"2,355",3.6%,"484,510",40.5%,"435,018",53.4%,"49,492",12.9%
16,$300 to $499,"318,022",16.7%,"268,488",20.3%,"49,534",8.5%,"19,025",7.3%,"14,950",...,"29,331",17.7%,"4,568",7.0%,"138,543",11.6%,"72,811",8.9%,"65,732",17.2%
17,$500 to $799,"373,656",19.6%,"216,830",16.4%,"156,826",26.9%,"31,806",12.2%,"24,042",...,"25,483",15.4%,"17,687",27.1%,"192,681",16.1%,"116,577",14.3%,"76,104",19.9%
18,$800 to $999,"247,533",13.0%,"134,500",10.2%,"113,033",19.4%,"23,995",9.2%,"12,881",...,"11,767",7.1%,"12,933",19.8%,"91,000",7.6%,"68,590",8.4%,"22,410",5.9%
19,"$1,000 to $1,499","413,053",21.7%,"274,253",20.8%,"138,800",23.8%,"53,903",20.7%,"25,894",...,"34,078",20.6%,"15,353",23.5%,"92,575",7.7%,"77,739",9.5%,"14,836",3.9%

Then, we only keep the necessary columns containing data for California and Texas in all four tables for our analysis by filtering and removing other unnecessary states' columns. Simultaneously, we also need to rename columns.

In [78]:
df2020_sub = household_income_2020.filter(regex='California|Texas')
df2020_label = household_income_2020[['Label (Grouping)']]
household_income_2020 = df2020_label.merge(df2020_sub, left_index=True, right_index=True).reset_index(drop=True)
# Rename all columns
household_income_2020.rename(columns={'Label (Grouping)': 'Household Income 2020',
                                         'California!!Occupied housing units!!Estimate': 'California Occupied housing units',
                                        'California!!Percent occupied housing units!!Estimate': 'California Percent occupied housing units',
                                        'California!!Owner-occupied housing units!!Estimate': 'California Owner-occupied housing units',
                                        'California!!Percent owner-occupied housing units!!Estimate': 'California Percent owner-occupied housing units',
                                        'California!!Renter-occupied housing units!!Estimate': 'California Renter-occupied housing units',
                                        'California!!Percent renter-occupied housing units!!Estimate': 'California Percent renter-occupied housing units',
                                        'Texas!!Occupied housing units!!Estimate': 'Texas Occupied housing units',
                                        'Texas!!Percent occupied housing units!!Estimate': 'Texas Percent occupied housing units',
                                        'Texas!!Owner-occupied housing units!!Estimate': 'Texas Owner-occupied housing units',
                                        'Texas!!Percent owner-occupied housing units!!Estimate': 'Texas Percent owner-occupied housing units',
                                        'Texas!!Renter-occupied housing units!!Estimate': 'Texas Renter-occupied housing units',
                                        'Texas!!Percent renter-occupied housing units!!Estimate': 'Texas Percent renter-occupied housing units'},
                            inplace=True)

In [79]:
household_income_2020.head()

,Household Income 2020,California Occupied housing units,California Percent occupied housing units,California Owner-occupied housing units,California Percent owner-occupied housing units,California Renter-occupied housing units,California Percent renter-occupied housing units,Texas Occupied housing units,Texas Percent occupied housing units,Texas Owner-occupied housing units,Texas Percent owner-occupied housing units,Texas Renter-occupied housing units,Texas Percent renter-occupied housing units
0,"Less than $5,000","365,131",2.8%,"123,955",1.7%,"241,176",4.1%,"308,169",3.1%,"114,751",1.9%,"193,418",5.2%
1,"$5,000 to $9,999","249,756",1.9%,"77,011",1.1%,"172,745",2.9%,"283,676",2.9%,"98,814",1.6%,"184,862",4.9%
2,"$10,000 to $14,999","507,398",3.9%,"141,153",1.9%,"366,245",6.2%,"387,297",3.9%,"163,706",2.7%,"223,591",6.0%
3,"$15,000 to $19,999","435,382",3.3%,"152,387",2.1%,"282,995",4.8%,"398,380",4.0%,"173,492",2.8%,"224,888",6.0%
4,"$20,000 to $24,999","474,093",3.6%,"171,950",2.4%,"302,143",5.2%,"433,431",4.4%,"198,062",3.2%,"235,369",6.3%

In [80]:
df2020_cost_sub = housing_costs_2020.filter(regex='California|Texas')
df2020_cost_label = housing_costs_2020[['Label (Grouping)']]
housing_costs_2020 = df2020_cost_label.merge(df2020_cost_sub, left_index=True, right_index=True).reset_index(drop=True)
# Rename all columns
housing_costs_2020.rename(columns={'Label (Grouping)': 'Housing Cost 2020',
                                         'California!!Occupied housing units!!Estimate': 'California Occupied housing units',
                                        'California!!Percent occupied housing units!!Estimate': 'California Percent occupied housing units',
                                        'California!!Owner-occupied housing units!!Estimate': 'California Owner-occupied housing units',
                                        'California!!Percent owner-occupied housing units!!Estimate': 'California Percent owner-occupied housing units',
                                        'California!!Renter-occupied housing units!!Estimate': 'California Renter-occupied housing units',
                                        'California!!Percent renter-occupied housing units!!Estimate': 'California Percent renter-occupied housing units',
                                        'Texas!!Occupied housing units!!Estimate': 'Texas Occupied housing units',
                                        'Texas!!Percent occupied housing units!!Estimate': 'Texas Percent occupied housing units',
                                        'Texas!!Owner-occupied housing units!!Estimate': 'Texas Owner-occupied housing units',
                                        'Texas!!Percent owner-occupied housing units!!Estimate': 'Texas Percent owner-occupied housing units',
                                        'Texas!!Renter-occupied housing units!!Estimate': 'Texas Renter-occupied housing units',
                                        'Texas!!Percent renter-occupied housing units!!Estimate': 'Texas Percent renter-occupied housing units'},
                            inplace=True)

In [81]:
housing_costs_2020.head()

,Housing Cost 2020,California Occupied housing units,California Percent occupied housing units,California Owner-occupied housing units,California Percent owner-occupied housing units,California Renter-occupied housing units,California Percent renter-occupied housing units,Texas Occupied housing units,Texas Percent occupied housing units,Texas Owner-occupied housing units,Texas Percent owner-occupied housing units,Texas Renter-occupied housing units,Texas Percent renter-occupied housing units
0,Less than $300,"390,873",3.0%,"274,063",3.8%,"116,810",2.0%,"566,753",5.7%,"479,784",7.8%,"86,969",2.3%
1,$300 to $499,"682,136",5.2%,"535,640",7.4%,"146,496",2.5%,"927,528",9.4%,"795,265",12.9%,"132,263",3.5%
2,$500 to $799,"1,164,232",8.9%,"799,003",11.0%,"365,229",6.2%,"1,577,474",15.9%,"986,195",16.0%,"591,279",15.8%
3,$800 to $999,"879,823",6.7%,"418,214",5.8%,"461,609",7.9%,"1,252,434",12.6%,"541,659",8.8%,"710,775",19.0%
4,"$1,000 to $1,499","2,431,992",18.6%,"914,962",12.6%,"1,517,030",25.9%,"2,501,018",25.2%,"1,203,053",19.5%,"1,297,965",34.7%

In [82]:
df2021_sub = household_income_2021.filter(regex='California|Texas')
df2021_label = household_income_2021[['Label (Grouping)']]
household_income_2021 = df2021_label.merge(df2021_sub, left_index=True, right_index=True).reset_index(drop=True)
# Rename all columns
household_income_2021.rename(columns={'Label (Grouping)': 'Household Income 2021',
                                         'California!!Occupied housing units!!Estimate': 'California Occupied housing units',
                                        'California!!Percent occupied housing units!!Estimate': 'California Percent occupied housing units',
                                        'California!!Owner-occupied housing units!!Estimate': 'California Owner-occupied housing units',
                                        'California!!Percent owner-occupied housing units!!Estimate': 'California Percent owner-occupied housing units',
                                        'California!!Renter-occupied housing units!!Estimate': 'California Renter-occupied housing units',
                                        'California!!Percent renter-occupied housing units!!Estimate': 'California Percent renter-occupied housing units',
                                        'Texas!!Occupied housing units!!Estimate': 'Texas Occupied housing units',
                                        'Texas!!Percent occupied housing units!!Estimate': 'Texas Percent occupied housing units',
                                        'Texas!!Owner-occupied housing units!!Estimate': 'Texas Owner-occupied housing units',
                                        'Texas!!Percent owner-occupied housing units!!Estimate': 'Texas Percent owner-occupied housing units',
                                        'Texas!!Renter-occupied housing units!!Estimate': 'Texas Renter-occupied housing units',
                                        'Texas!!Percent renter-occupied housing units!!Estimate': 'Texas Percent renter-occupied housing units'},
                            inplace=True)

In [83]:
household_income_2021.head()

,Household Income 2021,California Occupied housing units,California Percent occupied housing units,California Owner-occupied housing units,California Percent owner-occupied housing units,California Renter-occupied housing units,California Percent renter-occupied housing units,Texas Occupied housing units,Texas Percent occupied housing units,Texas Owner-occupied housing units,Texas Percent owner-occupied housing units,Texas Renter-occupied housing units,Texas Percent renter-occupied housing units
0,"Less than $5,000","374,538",2.8%,"127,930",1.7%,"246,608",4.2%,"321,026",3.1%,"121,766",1.9%,"199,260",5.2%
1,"$5,000 to $9,999","233,791",1.8%,"74,986",1.0%,"158,805",2.7%,"261,778",2.6%,"91,950",1.4%,"169,828",4.4%
2,"$10,000 to $14,999","471,825",3.6%,"130,839",1.8%,"340,986",5.8%,"381,790",3.7%,"158,169",2.5%,"223,621",5.8%
3,"$15,000 to $19,999","395,789",3.0%,"140,447",1.9%,"255,342",4.3%,"380,507",3.7%,"166,521",2.6%,"213,986",5.6%
4,"$20,000 to $24,999","428,857",3.2%,"155,752",2.1%,"273,105",4.6%,"413,003",4.0%,"184,101",2.9%,"228,902",5.9%

In [84]:
df2021_cost_sub = housing_costs_2021.filter(regex='California|Texas')
df2021_cost_label = housing_costs_2021[['Label (Grouping)']]
housing_costs_2021 = df2021_cost_label.merge(df2021_cost_sub, left_index=True, right_index=True).reset_index(drop=True)
# Rename all columns
housing_costs_2021.rename(columns={'Label (Grouping)': 'Housing Cost 2021',
                                         'California!!Occupied housing units!!Estimate': 'California Occupied housing units',
                                        'California!!Percent occupied housing units!!Estimate': 'California Percent occupied housing units',
                                        'California!!Owner-occupied housing units!!Estimate': 'California Owner-occupied housing units',
                                        'California!!Percent owner-occupied housing units!!Estimate': 'California Percent owner-occupied housing units',
                                        'California!!Renter-occupied housing units!!Estimate': 'California Renter-occupied housing units',
                                        'California!!Percent renter-occupied housing units!!Estimate': 'California Percent renter-occupied housing units',
                                        'Texas!!Occupied housing units!!Estimate': 'Texas Occupied housing units',
                                        'Texas!!Percent occupied housing units!!Estimate': 'Texas Percent occupied housing units',
                                        'Texas!!Owner-occupied housing units!!Estimate': 'Texas Owner-occupied housing units',
                                        'Texas!!Percent owner-occupied housing units!!Estimate': 'Texas Percent owner-occupied housing units',
                                        'Texas!!Renter-occupied housing units!!Estimate': 'Texas Renter-occupied housing units',
                                        'Texas!!Percent renter-occupied housing units!!Estimate': 'Texas Percent renter-occupied housing units'},
                            inplace=True)

In [85]:
housing_costs_2021.head()

,Housing Cost 2021,California Occupied housing units,California Percent occupied housing units,California Owner-occupied housing units,California Percent owner-occupied housing units,California Renter-occupied housing units,California Percent renter-occupied housing units,Texas Occupied housing units,Texas Percent occupied housing units,Texas Owner-occupied housing units,Texas Percent owner-occupied housing units,Texas Renter-occupied housing units,Texas Percent renter-occupied housing units
0,Less than $300,"345,057",2.6%,"240,816",3.3%,"104,241",1.8%,"523,817",5.1%,"443,518",6.9%,"80,299",2.1%
1,$300 to $499,"632,527",4.8%,"491,535",6.7%,"140,992",2.4%,"886,569",8.7%,"768,140",12.0%,"118,429",3.1%
2,$500 to $799,"1,099,679",8.3%,"793,823",10.8%,"305,856",5.2%,"1,488,015",14.5%,"994,817",15.6%,"493,198",12.8%
3,$800 to $999,"795,024",6.0%,"421,015",5.7%,"374,009",6.4%,"1,200,447",11.7%,"540,910",8.5%,"659,537",17.1%
4,"$1,000 to $1,499","2,274,180",17.2%,"895,404",12.2%,"1,378,776",23.4%,"2,607,562",25.5%,"1,199,749",18.8%,"1,407,813",36.6%

Now, we will create some helper functions such as:
- `reset_index`: to reset the index and rename the new column to 'Income Bracket', 'Housing Cost', or 'Household Income' with a condition to check if 'Income Bracket', 'Housing Cost', or 'Household Income'.
- `drop_column`: to drop the 'Label (Grouping)' column.
- `merge_data`: to merge the dataframes
- `rm_yr_state`: to check if the columns contain the year and state then remove the year and state on the column name.
- `check_and_rename`: to check and rename the columns, set year and state.

In [86]:
# Function to Reset the index and rename the new column to 'Income Bracket', 'Housing Cost', or 'Household Income'
# Having a condition to check if 'Income Bracket', 'Housing Cost', or 'Household Income'
def reset_index(df, column_name):
    df = df.reset_index(drop=True)
    df.rename(columns={'Label (Grouping)': column_name}, inplace=True)
    return df

# Function to drop the 'Label (Grouping)' column
def drop_column(df):
    df = df.drop(columns=['Label (Grouping)'])
    return df

# Function to merge the dataframes
def merge_data(df1, df2, df3):
    df = df1.merge(df2, left_index=True, right_index=True).merge(df3, left_index=True, right_index=True)
    return df

# Function to check if the columns contain the year and state then remove the year and state on the column name
def rm_yr_state(df, year, state):
    rename_dict = {}

    # Iterate through each column in the dataframe
    for col in df.columns:
        # Replace the state and year in the column name with an empty string
        new_col = col.replace(str(year), '').replace(state, '').strip()
        rename_dict[col] = new_col

    # Rename the columns using the dictionary
    df = df.rename(columns=rename_dict)

    return df


# Define a function to check and rename the columns, set year and state
def check_and_rename(df, year, state):
    # Check if the dataframe contains 'Income Bracket', 'Housing Cost', or 'Household Income'
    if 'Income Bracket' in df.columns:
        # Rename the column to 'Income Bracket' and drop the 'Label (Grouping)' column
        df = reset_index(df, 'Income Bracket')
        df = drop_column(df)
    elif 'Housing Cost' in df.columns:
        # Rename the column to 'Housing Cost' and drop the 'Label (Grouping)' column
        df = reset_index(df, 'Housing Cost')
        df = drop_column(df)
    elif 'Household Income' in df.columns:
        # Rename the column to 'Household Income' and drop the 'Label (Grouping)' column
        df = reset_index(df, 'Household Income')
        df = drop_column(df)
    
    # Set the year and state
    df['Year'] = year
    df['State'] = state

    # Remove the year and state on the column name
    df = rm_yr_state(df, year, state)

    return df

Then, we extract California and Texas data separately before creating reference tables for housing costs and household income and merging the reference tables with the existing DataFrames so that we can concatenate all the DataFrames together and reset the index after that.

In [87]:
# Extract California and Texas data separately
# 2020
housing_costs_2020_ca = housing_costs_2020[[col for col in housing_costs_2020.columns if 'California' in col or 'Housing Cost' in col]]
housing_costs_2020_tx = housing_costs_2020[[col for col in housing_costs_2020.columns if 'Texas' in col or 'Housing Cost' in col]]
household_income_2020_ca = household_income_2020[[col for col in household_income_2020.columns if 'California' in col or 'Household Income' in col]]
household_income_2020_tx = household_income_2020[[col for col in household_income_2020.columns if 'Texas' in col or 'Household Income' in col]]

california_housing_costs_2020 = check_and_rename(housing_costs_2020_ca, '2020', 'California')
texas_housing_costs_2020 = check_and_rename(housing_costs_2020_tx, '2020', 'Texas')
california_household_income_2020 = check_and_rename(household_income_2020_ca, '2020', 'California')
texas_household_income_2020 = check_and_rename(household_income_2020_tx, '2020', 'Texas')

# 2021
housing_costs_2021_ca = housing_costs_2021[[col for col in housing_costs_2021.columns if 'California' in col or 'Housing Cost' in col]]
housing_costs_2021_tx = housing_costs_2021[[col for col in housing_costs_2021.columns if 'Texas' in col or 'Housing Cost' in col]]
household_income_2021_ca = household_income_2021[[col for col in household_income_2021.columns if 'California' in col or 'Household Income' in col]]
household_income_2021_tx = household_income_2021[[col for col in household_income_2021.columns if 'Texas' in col or 'Household Income' in col]]

california_housing_costs_2021 = check_and_rename(housing_costs_2021_ca, '2021', 'California')
texas_housing_costs_2021 = check_and_rename(housing_costs_2021_tx, '2021', 'Texas')
california_household_income_2021 = check_and_rename(household_income_2021_ca, '2021', 'California')
texas_household_income_2021 = check_and_rename(household_income_2021_tx, '2021', 'Texas')

Meanwhile, we will also format data for achieving consistency and improving the quality of the data for further analysis and decision-making.

In [88]:
# Create a reference table for housing costs
housing_cost_ref = pd.DataFrame(california_housing_costs_2020['Housing Cost'].unique(), columns=['Housing Cost'])
housing_cost_ref['Cost Index'] = housing_cost_ref.index
housing_cost_ref_copy = housing_cost_ref.copy()
housing_cost_ref_copy = housing_cost_ref_copy.rename(columns={'Housing Cost': 'Housing Cost (Dollars)'})

# Formatting data
# Replace "to" with "-"
housing_cost_ref_copy['Housing Cost (Dollars)'] = housing_cost_ref_copy['Housing Cost (Dollars)'].str.replace('to', '-')

# Remove all "$" and "dollars"
housing_cost_ref_copy['Housing Cost (Dollars)'] = housing_cost_ref_copy['Housing Cost (Dollars)'].str.replace('$', '', regex=False)
housing_cost_ref_copy['Housing Cost (Dollars)'] = housing_cost_ref_copy['Housing Cost (Dollars)'].str.replace('(dollars)', '', regex=False)

# Replace "Less than" and "or more"
housing_cost_ref_copy['Housing Cost (Dollars)'] = housing_cost_ref_copy['Housing Cost (Dollars)'].str.replace('Less than', '<')
housing_cost_ref_copy['Housing Cost (Dollars)'] = housing_cost_ref_copy['Housing Cost (Dollars)'].str.replace('3,000 or more', '≥ 3000')
housing_cost_ref_copy

   Housing Cost (Dollars)  Cost Index
0                   < 300           0
1               300 - 499           1
2               500 - 799           2
3               800 - 999           3
4           1,000 - 1,499           4
5           1,500 - 1,999           5
6           2,000 - 2,499           6
7           2,500 - 2,999           7
8                  ≥ 3000           8
9            No cash rent           9
10                Median           10

In [89]:
# Create a reference table for household income
household_income_ref = pd.DataFrame(california_household_income_2020['Household Income'].unique(), columns=['Household Income'])
household_income_ref['Income Index'] = household_income_ref.index
household_income_ref_copy = household_income_ref.copy()
household_income_ref_copy = household_income_ref_copy .rename(columns={'Household Income': 'Household Income (Dollars)'})

# Formatting data
# Replace "to" with "-"
household_income_ref_copy['Household Income (Dollars)'] = household_income_ref_copy['Household Income (Dollars)'].str.replace('to', '-')

# Remove all "$"
household_income_ref_copy['Household Income (Dollars)'] = household_income_ref_copy['Household Income (Dollars)'].str.replace('$', '', regex=False)
household_income_ref_copy['Household Income (Dollars)'] = household_income_ref_copy['Household Income (Dollars)'].str.replace('(dollars)', '', regex=False)

# Replace "Less than" and "or more"
household_income_ref_copy['Household Income (Dollars)'] = household_income_ref_copy['Household Income (Dollars)'].str.replace('Less than', '<')
household_income_ref_copy['Household Income (Dollars)'] = household_income_ref_copy['Household Income (Dollars)'].str.replace('150,000 or more', '≥ 150,000')
household_income_ref_copy

          Household Income (Dollars)  Income Index
0                            < 5,000             0
1                      5,000 - 9,999             1
2                    10,000 - 14,999             2
3                    15,000 - 19,999             3
4                    20,000 - 24,999             4
5                    25,000 - 34,999             5
6                    35,000 - 49,999             6
7                    50,000 - 74,999             7
8                    75,000 - 99,999             8
9                  100,000 - 149,999             9
10                         ≥ 150,000            10
11          Median household income             11

In [90]:
# Change column name "Housing Cost (Dollars)" = "Housing Cost" and "Household Income (Dollars)" = "Household Income" to sync with other tables
housing_cost_ref = housing_cost_ref.rename(columns={'Housing Cost (Dollars)': 'Housing Cost'})
household_income_ref = household_income_ref.rename(columns={'Household Income (Dollars)': 'Household Income'})

# Merge the reference table with the existing DataFrames
# Housing Costs
california_housing_costs_2020 = california_housing_costs_2020.merge(housing_cost_ref, on='Housing Cost')
texas_housing_costs_2020 = texas_housing_costs_2020.merge(housing_cost_ref, on='Housing Cost')
california_housing_costs_2021 = california_housing_costs_2021.merge(housing_cost_ref, on='Housing Cost')
texas_housing_costs_2021 = texas_housing_costs_2021.merge(housing_cost_ref, on='Housing Cost')

# Household Income
california_household_income_2020 = california_household_income_2020.merge(household_income_ref, on='Household Income')
texas_household_income_2020 = texas_household_income_2020.merge(household_income_ref, on='Household Income')
california_household_income_2021 = california_household_income_2021.merge(household_income_ref, on='Household Income')
texas_household_income_2021 = texas_household_income_2021.merge(household_income_ref, on='Household Income')

In [91]:
# Concatenate all the DataFrames together
housing_costs = pd.concat([california_housing_costs_2020, texas_housing_costs_2020, california_housing_costs_2021, texas_housing_costs_2021])
household_income = pd.concat([california_household_income_2020, texas_household_income_2020, california_household_income_2021, texas_household_income_2021])

# Reset the index
housing_costs.reset_index(drop=True, inplace=True)
household_income.reset_index(drop=True, inplace=True)

Next, before merging both dataframes `housing_costs` and `household_income`, we need to convert the reference dataframes to dictionaries, replace the values in the original dataframes, copy the dataframes to avoid changing the original data, add a prefix to the column names of each dataframe. After that, we can drop the duplicate columns.

In [92]:
# Convert the reference dataframes to dictionaries
household_income_ref_dict = household_income_ref.set_index('Household Income')['Income Index'].to_dict()
housing_costs_ref_dict = housing_cost_ref.set_index('Housing Cost')['Cost Index'].to_dict()

# Replace the values in the original dataframes
housing_costs['Housing Cost'] = housing_costs['Housing Cost'].map(housing_costs_ref_dict)
household_income['Household Income'] = household_income['Household Income'].map(household_income_ref_dict)

# Copy the dataframes to avoid changing the original data
housing_costs_copy = housing_costs.copy()
household_income_copy = household_income.copy()

# Add a prefix to the column names of each dataframe
housing_costs_copy.columns = ['Housing ' + col if col not in ['Year', 'State', 'Housing Cost'] else col for col in housing_costs.columns]
household_income_copy.columns = ['Income ' + col if col not in ['Year', 'State', 'Household Income'] else col for col in household_income.columns]

# Now perform the merge
df = pd.merge(housing_costs_copy, household_income_copy,  how='left', 
                       left_on=['Year','State','Housing Cost'], 
                       right_on = ['Year','State','Household Income'])

# Drop the duplicate columns
df.drop(['Household Income', 'Housing Cost'], axis=1, inplace=True)
df

,Housing Occupied housing units,Housing Percent occupied housing units,Housing Owner-occupied housing units,Housing Percent owner-occupied housing units,Housing Renter-occupied housing units,Housing Percent renter-occupied housing units,Year,State,Housing Cost Index,Income Occupied housing units,Income Percent occupied housing units,Income Owner-occupied housing units,Income Percent owner-occupied housing units,Income Renter-occupied housing units,Income Percent renter-occupied housing units,Income Income Index
0,"390,873",3.0%,"274,063",3.8%,"116,810",2.0%,2020,California,0,"365,131",2.8%,"123,955",1.7%,"241,176",4.1%,0
1,"682,136",5.2%,"535,640",7.4%,"146,496",2.5%,2020,California,1,"249,756",1.9%,"77,011",1.1%,"172,745",2.9%,1
2,"1,164,232",8.9%,"799,003",11.0%,"365,229",6.2%,2020,California,2,"507,398",3.9%,"141,153",1.9%,"366,245",6.2%,2
3,"879,823",6.7%,"418,214",5.8%,"461,609",7.9%,2020,California,3,"435,382",3.3%,"152,387",2.1%,"282,995",4.8%,3
4,"2,431,992",18.6%,"914,962",12.6%,"1,517,030",25.9%,2020,California,4,"474,093",3.6%,"171,950",2.4%,"302,143",5.2%,4
5,"2,320,070",17.7%,"970,820",13.4%,"1,349,250",23.0%,2020,California,5,"929,716",7.1%,"367,684",5.1%,"562,032",9.6%,5
6,"1,732,363",13.2%,"911,537",12.6%,"820,826",14.0%,2020,California,6,"1,316,064",10.0%,"568,329",7.8%,"747,735",12.8%,6
7,"1,175,576",9.0%,"741,370",10.2%,"434,206",7.4%,2020,California,7,"2,007,523",15.3%,"988,205",13.6%,"1,019,318",17.4%,7
8,"2,142,269",16.3%,"1,675,709",23.1%,"466,560",8.0%,2020,California,8,"1,616,338",12.3%,"918,798",12.7%,"697,540",11.9%,8
9,"183,780",1.4%,(X),(X),"183,780",3.1%,2020,California,9,"2,235,114",17.1%,"1,457,430",20.1%,"777,684",13.3%,9
10,"1,688","1,688","1,851","1,851","1,586","1,586",2020,California,10,"2,966,599",22.6%,"2,274,416",31.4%,"692,183",11.8%,10
11,"566,753",5.7%,"479,784",7.8%,"86,969",2.3%,2020,Texas,0,"308,169",3.1%,"114,751",1.9%,"193,418",5.2%,0
12,"927,528",9.4%,"795,265",12.9%,"132,263",3.5%,2020,Texas,1,"283,676",2.9%,"98,814",1.6%,"184,862",4.9%,1
13,"1,577,474",15.9%,"986,195",16.0%,"591,279",15.8%,2020,Texas,2,"387,297",3.9%,"163,706",2.7%,"223,591",6.0%,2
14,"1,252,434",12.6%,"541,659",8.8%,"710,775",19.0%,2020,Texas,3,"398,380",4.0%,"173,492",2.8%,"224,888",6.0%,3
15,"2,501,018",25.2%,"1,203,053",19.5%,"1,297,965",34.7%,2020,Texas,4,"433,431",4.4%,"198,062",3.2%,"235,369",6.3%,4
16,"1,434,072",14.5%,"921,171",14.9%,"512,901",13.7%,2020,Texas,5,"880,917",8.9%,"416,621",6.8%,"464,296",12.4%,5
17,"669,574",6.8%,"521,198",8.4%,"148,376",4.0%,2020,Texas,6,"1,217,734",12.3%,"631,735",10.2%,"585,999",15.7%,6
18,"339,803",3.4%,"297,189",4.8%,"42,614",1.1%,2020,Texas,7,"1,740,601",17.6%,"1,027,478",16.7%,"713,123",19.1%,7
19,"458,134",4.6%,"423,294",6.9%,"34,840",0.9%,2020,Texas,8,"1,242,248",12.5%,"853,357",13.8%,"388,891",10.4%,8
20,"179,280",1.8%,(X),(X),"179,280",4.8%,2020,Texas,9,"1,546,177",15.6%,"1,203,076",19.5%,"343,101",9.2%,9
21,"1,095","1,095","1,113","1,113","1,082","1,082",2020,Texas,10,"1,467,440",14.8%,"1,287,716",20.9%,"179,724",4.8%,10
22,"345,057",2.6%,"240,816",3.3%,"104,241",1.8%,2021,California,0,"374,538",2.8%,"127,930",1.7%,"246,608",4.2%,0
23,"632,527",4.8%,"491,535",6.7%,"140,992",2.4%,2021,California,1,"233,791",1.8%,"74,986",1.0%,"158,805",2.7%,1
24,"1,099,679",8.3%,"793,823",10.8%,"305,856",5.2%,2021,California,2,"471,825",3.6%,"130,839",1.8%,"340,986",5.8%,2
25,"795,024",6.0%,"421,015",5.7%,"374,009",6.4%,2021,California,3,"395,789",3.0%,"140,447",1.9%,"255,342",4.3%,3
26,"2,274,180",17.2%,"895,404",12.2%,"1,378,776",23.4%,2021,California,4,"428,857",3.2%,"155,752",2.1%,"273,105",4.6%,4
27,"2,307,994",17.5%,"934,791",12.7%,"1,373,203",23.3%,2021,California,5,"882,663",6.7%,"343,803",4.7%,"538,860",9.2%,5
28,"1,825,351",13.8%,"900,633",12.3%,"924,718",15.7%,2021,California,6,"1,239,134",9.4%,"531,604",7.2%,"707,530",12.0%,6
29,"1,268,311",9.6%,"767,569",10.5%,"500,742",8.5%,2021,California,7,"1,947,417",14.7%,"938,296",12.8%,"1,009,121",17.2%,7
30,"2,484,952",18.8%,"1,889,661",25.8%,"595,291",10.1%,2021,California,8,"1,621,793",12.3%,"896,086",12.2%,"725,707",12.3%,8
31,"184,511",1.4%,(X),(X),"184,511",3.1%,2021,California,9,"2,310,752",17.5%,"1,478,550",20.2%,"832,202",14.1%,9
32,"1,791","1,791","1,943","1,943","1,698","1,698",2021,California,10,"3,311,027",25.1%,"2,516,954",34.3%,"794,073",13.5%,10
33,"523,817",5.1%,"443,518",6.9%,"80,299",2.1%,2021,Texas,0,"321,026",3.1%,"121,766",1.9%,"199,260",5.2%,0
34,"886,569",8.7%,"768,140",12.0%,"118,429",3.1%,2021,Texas,1,"261,778",2.6%,"91,950",1.4%,"169,828",4.4%,1
35,"1,488,015",14.5%,"994,817",15.6%,"493,198",12.8%,2021,Texas,2,"381,790",3.7%,"158,169",2.5%,"223,621",5.8%,2
36,"1,200,447",11.7%,"540,910",8.5%,"659,537",17.1%,2021,Texas,3,"380,507",3.7%,"166,521",2.6%,"213,986",5.6%,3
37,"2,607,562",25.5%,"1,199,749",18.8%,"1,407,813",36.6%,2021,Texas,4,"413,003",4.0%,"184,101",2.9%,"228,902",5.9%,4
38,"1,602,456",15.6%,"986,293",15.4%,"616,163",16.0%,2021,Texas,5,"870,908",8.5%,"405,983",6.4%,"464,925",12.1%,5
39,"799,437",7.8%,"603,296",9.4%,"196,141",5.1%,2021,Texas,6,"1,201,280",11.7%,"610,136",9.5%,"591,144",15.4%,6
40,"396,866",3.9%,"346,272",5.4%,"50,594",1.3%,2021,Texas,7,"1,767,665",17.3%,"1,022,954",16.0%,"744,711",19.4%,7
41,"553,351",5.4%,"508,066",7.9%,"45,285",1.2%,2021,Texas,8,"1,297,103",12.7%,"878,896",13.8%,"418,207",10.9%,8
42,"180,821",1.8%,(X),(X),"180,821",4.7%,2021,Texas,9,"1,661,203",16.2%,"1,278,904",20.0%,"382,299",9.9%,9
43,"1,161","1,161","1,181","1,181","1,146","1,146",2021,Texas,10,"1,683,078",16.4%,"1,471,681",23.0%,"211,397",5.5%,10

We will now count the number of missing values represented as `(X)` in the data frame.

In [93]:
# Check if (X) is present in the dataframe for missing values, count the number of missing values
df.isin(['(X)']).sum()

Housing Occupied housing units                   0
Housing Percent occupied housing units           0
Housing Owner-occupied housing units             4
Housing Percent owner-occupied housing units     4
Housing Renter-occupied housing units            0
Housing Percent renter-occupied housing units    0
Year                                             0
State                                            0
Housing Cost Index                               0
Income Occupied housing units                    0
Income Percent occupied housing units            0
Income Owner-occupied housing units              0
Income Percent owner-occupied housing units      0
Income Renter-occupied housing units             0
Income Percent renter-occupied housing units     0
Income Income Index                              0
dtype: int64

Since we have only 48 value of (X), we can remove the rows with (X) in the 2020 and 2021 Household Income tables because we have enough data to analyze.

In [94]:
# Drop the rows with missing values
df = df[~df.isin(['(X)'])]
df

,Housing Occupied housing units,Housing Percent occupied housing units,Housing Owner-occupied housing units,Housing Percent owner-occupied housing units,Housing Renter-occupied housing units,Housing Percent renter-occupied housing units,Year,State,Housing Cost Index,Income Occupied housing units,Income Percent occupied housing units,Income Owner-occupied housing units,Income Percent owner-occupied housing units,Income Renter-occupied housing units,Income Percent renter-occupied housing units,Income Income Index
0,"390,873",3.0%,"274,063",3.8%,"116,810",2.0%,2020,California,0,"365,131",2.8%,"123,955",1.7%,"241,176",4.1%,0
1,"682,136",5.2%,"535,640",7.4%,"146,496",2.5%,2020,California,1,"249,756",1.9%,"77,011",1.1%,"172,745",2.9%,1
2,"1,164,232",8.9%,"799,003",11.0%,"365,229",6.2%,2020,California,2,"507,398",3.9%,"141,153",1.9%,"366,245",6.2%,2
3,"879,823",6.7%,"418,214",5.8%,"461,609",7.9%,2020,California,3,"435,382",3.3%,"152,387",2.1%,"282,995",4.8%,3
4,"2,431,992",18.6%,"914,962",12.6%,"1,517,030",25.9%,2020,California,4,"474,093",3.6%,"171,950",2.4%,"302,143",5.2%,4
5,"2,320,070",17.7%,"970,820",13.4%,"1,349,250",23.0%,2020,California,5,"929,716",7.1%,"367,684",5.1%,"562,032",9.6%,5
6,"1,732,363",13.2%,"911,537",12.6%,"820,826",14.0%,2020,California,6,"1,316,064",10.0%,"568,329",7.8%,"747,735",12.8%,6
7,"1,175,576",9.0%,"741,370",10.2%,"434,206",7.4%,2020,California,7,"2,007,523",15.3%,"988,205",13.6%,"1,019,318",17.4%,7
8,"2,142,269",16.3%,"1,675,709",23.1%,"466,560",8.0%,2020,California,8,"1,616,338",12.3%,"918,798",12.7%,"697,540",11.9%,8
9,"183,780",1.4%,NaN,NaN,"183,780",3.1%,2020,California,9,"2,235,114",17.1%,"1,457,430",20.1%,"777,684",13.3%,9
10,"1,688","1,688","1,851","1,851","1,586","1,586",2020,California,10,"2,966,599",22.6%,"2,274,416",31.4%,"692,183",11.8%,10
11,"566,753",5.7%,"479,784",7.8%,"86,969",2.3%,2020,Texas,0,"308,169",3.1%,"114,751",1.9%,"193,418",5.2%,0
12,"927,528",9.4%,"795,265",12.9%,"132,263",3.5%,2020,Texas,1,"283,676",2.9%,"98,814",1.6%,"184,862",4.9%,1
13,"1,577,474",15.9%,"986,195",16.0%,"591,279",15.8%,2020,Texas,2,"387,297",3.9%,"163,706",2.7%,"223,591",6.0%,2
14,"1,252,434",12.6%,"541,659",8.8%,"710,775",19.0%,2020,Texas,3,"398,380",4.0%,"173,492",2.8%,"224,888",6.0%,3
15,"2,501,018",25.2%,"1,203,053",19.5%,"1,297,965",34.7%,2020,Texas,4,"433,431",4.4%,"198,062",3.2%,"235,369",6.3%,4
16,"1,434,072",14.5%,"921,171",14.9%,"512,901",13.7%,2020,Texas,5,"880,917",8.9%,"416,621",6.8%,"464,296",12.4%,5
17,"669,574",6.8%,"521,198",8.4%,"148,376",4.0%,2020,Texas,6,"1,217,734",12.3%,"631,735",10.2%,"585,999",15.7%,6
18,"339,803",3.4%,"297,189",4.8%,"42,614",1.1%,2020,Texas,7,"1,740,601",17.6%,"1,027,478",16.7%,"713,123",19.1%,7
19,"458,134",4.6%,"423,294",6.9%,"34,840",0.9%,2020,Texas,8,"1,242,248",12.5%,"853,357",13.8%,"388,891",10.4%,8
20,"179,280",1.8%,NaN,NaN,"179,280",4.8%,2020,Texas,9,"1,546,177",15.6%,"1,203,076",19.5%,"343,101",9.2%,9
21,"1,095","1,095","1,113","1,113","1,082","1,082",2020,Texas,10,"1,467,440",14.8%,"1,287,716",20.9%,"179,724",4.8%,10
22,"345,057",2.6%,"240,816",3.3%,"104,241",1.8%,2021,California,0,"374,538",2.8%,"127,930",1.7%,"246,608",4.2%,0
23,"632,527",4.8%,"491,535",6.7%,"140,992",2.4%,2021,California,1,"233,791",1.8%,"74,986",1.0%,"158,805",2.7%,1
24,"1,099,679",8.3%,"793,823",10.8%,"305,856",5.2%,2021,California,2,"471,825",3.6%,"130,839",1.8%,"340,986",5.8%,2
25,"795,024",6.0%,"421,015",5.7%,"374,009",6.4%,2021,California,3,"395,789",3.0%,"140,447",1.9%,"255,342",4.3%,3
26,"2,274,180",17.2%,"895,404",12.2%,"1,378,776",23.4%,2021,California,4,"428,857",3.2%,"155,752",2.1%,"273,105",4.6%,4
27,"2,307,994",17.5%,"934,791",12.7%,"1,373,203",23.3%,2021,California,5,"882,663",6.7%,"343,803",4.7%,"538,860",9.2%,5
28,"1,825,351",13.8%,"900,633",12.3%,"924,718",15.7%,2021,California,6,"1,239,134",9.4%,"531,604",7.2%,"707,530",12.0%,6
29,"1,268,311",9.6%,"767,569",10.5%,"500,742",8.5%,2021,California,7,"1,947,417",14.7%,"938,296",12.8%,"1,009,121",17.2%,7
30,"2,484,952",18.8%,"1,889,661",25.8%,"595,291",10.1%,2021,California,8,"1,621,793",12.3%,"896,086",12.2%,"725,707",12.3%,8
31,"184,511",1.4%,NaN,NaN,"184,511",3.1%,2021,California,9,"2,310,752",17.5%,"1,478,550",20.2%,"832,202",14.1%,9
32,"1,791","1,791","1,943","1,943","1,698","1,698",2021,California,10,"3,311,027",25.1%,"2,516,954",34.3%,"794,073",13.5%,10
33,"523,817",5.1%,"443,518",6.9%,"80,299",2.1%,2021,Texas,0,"321,026",3.1%,"121,766",1.9%,"199,260",5.2%,0
34,"886,569",8.7%,"768,140",12.0%,"118,429",3.1%,2021,Texas,1,"261,778",2.6%,"91,950",1.4%,"169,828",4.4%,1
35,"1,488,015",14.5%,"994,817",15.6%,"493,198",12.8%,2021,Texas,2,"381,790",3.7%,"158,169",2.5%,"223,621",5.8%,2
36,"1,200,447",11.7%,"540,910",8.5%,"659,537",17.1%,2021,Texas,3,"380,507",3.7%,"166,521",2.6%,"213,986",5.6%,3
37,"2,607,562",25.5%,"1,199,749",18.8%,"1,407,813",36.6%,2021,Texas,4,"413,003",4.0%,"184,101",2.9%,"228,902",5.9%,4
38,"1,602,456",15.6%,"986,293",15.4%,"616,163",16.0%,2021,Texas,5,"870,908",8.5%,"405,983",6.4%,"464,925",12.1%,5
39,"799,437",7.8%,"603,296",9.4%,"196,141",5.1%,2021,Texas,6,"1,201,280",11.7%,"610,136",9.5%,"591,144",15.4%,6
40,"396,866",3.9%,"346,272",5.4%,"50,594",1.3%,2021,Texas,7,"1,767,665",17.3%,"1,022,954",16.0%,"744,711",19.4%,7
41,"553,351",5.4%,"508,066",7.9%,"45,285",1.2%,2021,Texas,8,"1,297,103",12.7%,"878,896",13.8%,"418,207",10.9%,8
42,"180,821",1.8%,NaN,NaN,"180,821",4.7%,2021,Texas,9,"1,661,203",16.2%,"1,278,904",20.0%,"382,299",9.9%,9
43,"1,161","1,161","1,181","1,181","1,146","1,146",2021,Texas,10,"1,683,078",16.4%,"1,471,681",23.0%,"211,397",5.5%,10

In [95]:
df.dtypes

Housing Occupied housing units                   object
Housing Percent occupied housing units           object
Housing Owner-occupied housing units             object
Housing Percent owner-occupied housing units     object
Housing Renter-occupied housing units            object
Housing Percent renter-occupied housing units    object
Year                                             object
State                                            object
Housing Cost Index                                int64
Income Occupied housing units                    object
Income Percent occupied housing units            object
Income Owner-occupied housing units              object
Income Percent owner-occupied housing units      object
Income Renter-occupied housing units             object
Income Percent renter-occupied housing units     object
Income Income Index                               int64
dtype: object

This DataFrame contains a number of data cleaning tasks:

1. **Removing the '%' character and converting to numerical format:** Columns like "Housing Percent occupied housing units", "Housing Percent owner-occupied housing units", "Housing Percent renter-occupied housing units", "Income Percent occupied housing units", "Income Percent owner-occupied housing units" and "Income Percent renter-occupied housing units" appear to be percentage values stored as strings. To convert these into a numerical format, we should remove the '%' character and convert the strings to floats.

2. **Removing the ',' character and converting to numerical format:** Columns like "Housing Occupied housing units", "Housing Owner-occupied housing units", "Housing Renter-occupied housing units", "Income Occupied housing units", "Income Owner-occupied housing units" and "Income Renter-occupied housing units" appear to be numerical values stored as strings with comma as thousand separator. We should remove the ',' character and convert the strings to integers.

3. **Replacing 'NaN' with appropriate values:** In the "Housing Owner-occupied housing units" and "Income Owner-occupied housing units" columns, there are some 'NaN' values. Depending on the context, these might be replaced with zeros or dealt with using some other method.

4. **Converting 'Year' to numerical format:** The "Year" column should be converted to integer format.

In [96]:
# Remove the '%' character and convert to float
percent_cols = [col for col in df.columns if 'Percent' in col]
for col in percent_cols:
    if isinstance(df[col].iloc[0], str):
        df[col] = df[col].str.replace(',', '').str.rstrip('%').astype('float') / 100

# Remove the ',' character and convert to integer
num_cols = ["Housing Occupied housing units", "Housing Owner-occupied housing units", "Housing Renter-occupied housing units", 
            "Income Occupied housing units", "Income Owner-occupied housing units", "Income Renter-occupied housing units"]
for col in num_cols:
    df[col] = df[col].str.replace(',', '').astype('float')

# Replace 'NaN' with 0 (or any other method of handling NaN based on your context)
df.fillna(0, inplace=True)

# Convert 'Year' to integer
df['Year'] = df['Year'].astype('int')

In [97]:
df

,Housing Occupied housing units,Housing Percent occupied housing units,Housing Owner-occupied housing units,Housing Percent owner-occupied housing units,Housing Renter-occupied housing units,Housing Percent renter-occupied housing units,Year,State,Housing Cost Index,Income Occupied housing units,Income Percent occupied housing units,Income Owner-occupied housing units,Income Percent owner-occupied housing units,Income Renter-occupied housing units,Income Percent renter-occupied housing units,Income Income Index
0,390873.00,0.03,274063.00,0.04,116810.00,0.02,2020,California,0,365131.00,0.03,123955.00,0.02,241176.00,0.04,0
1,682136.00,0.05,535640.00,0.07,146496.00,0.03,2020,California,1,249756.00,0.02,77011.00,0.01,172745.00,0.03,1
2,1164232.00,0.09,799003.00,0.11,365229.00,0.06,2020,California,2,507398.00,0.04,141153.00,0.02,366245.00,0.06,2
3,879823.00,0.07,418214.00,0.06,461609.00,0.08,2020,California,3,435382.00,0.03,152387.00,0.02,282995.00,0.05,3
4,2431992.00,0.19,914962.00,0.13,1517030.00,0.26,2020,California,4,474093.00,0.04,171950.00,0.02,302143.00,0.05,4
5,2320070.00,0.18,970820.00,0.13,1349250.00,0.23,2020,California,5,929716.00,0.07,367684.00,0.05,562032.00,0.10,5
6,1732363.00,0.13,911537.00,0.13,820826.00,0.14,2020,California,6,1316064.00,0.10,568329.00,0.08,747735.00,0.13,6
7,1175576.00,0.09,741370.00,0.10,434206.00,0.07,2020,California,7,2007523.00,0.15,988205.00,0.14,1019318.00,0.17,7
8,2142269.00,0.16,1675709.00,0.23,466560.00,0.08,2020,California,8,1616338.00,0.12,918798.00,0.13,697540.00,0.12,8
9,183780.00,0.01,0.00,0.00,183780.00,0.03,2020,California,9,2235114.00,0.17,1457430.00,0.20,777684.00,0.13,9
10,1688.00,16.88,1851.00,18.51,1586.00,15.86,2020,California,10,2966599.00,0.23,2274416.00,0.31,692183.00,0.12,10
11,566753.00,0.06,479784.00,0.08,86969.00,0.02,2020,Texas,0,308169.00,0.03,114751.00,0.02,193418.00,0.05,0
12,927528.00,0.09,795265.00,0.13,132263.00,0.04,2020,Texas,1,283676.00,0.03,98814.00,0.02,184862.00,0.05,1
13,1577474.00,0.16,986195.00,0.16,591279.00,0.16,2020,Texas,2,387297.00,0.04,163706.00,0.03,223591.00,0.06,2
14,1252434.00,0.13,541659.00,0.09,710775.00,0.19,2020,Texas,3,398380.00,0.04,173492.00,0.03,224888.00,0.06,3
15,2501018.00,0.25,1203053.00,0.20,1297965.00,0.35,2020,Texas,4,433431.00,0.04,198062.00,0.03,235369.00,0.06,4
16,1434072.00,0.14,921171.00,0.15,512901.00,0.14,2020,Texas,5,880917.00,0.09,416621.00,0.07,464296.00,0.12,5
17,669574.00,0.07,521198.00,0.08,148376.00,0.04,2020,Texas,6,1217734.00,0.12,631735.00,0.10,585999.00,0.16,6
18,339803.00,0.03,297189.00,0.05,42614.00,0.01,2020,Texas,7,1740601.00,0.18,1027478.00,0.17,713123.00,0.19,7
19,458134.00,0.05,423294.00,0.07,34840.00,0.01,2020,Texas,8,1242248.00,0.12,853357.00,0.14,388891.00,0.10,8
20,179280.00,0.02,0.00,0.00,179280.00,0.05,2020,Texas,9,1546177.00,0.16,1203076.00,0.20,343101.00,0.09,9
21,1095.00,10.95,1113.00,11.13,1082.00,10.82,2020,Texas,10,1467440.00,0.15,1287716.00,0.21,179724.00,0.05,10
22,345057.00,0.03,240816.00,0.03,104241.00,0.02,2021,California,0,374538.00,0.03,127930.00,0.02,246608.00,0.04,0
23,632527.00,0.05,491535.00,0.07,140992.00,0.02,2021,California,1,233791.00,0.02,74986.00,0.01,158805.00,0.03,1
24,1099679.00,0.08,793823.00,0.11,305856.00,0.05,2021,California,2,471825.00,0.04,130839.00,0.02,340986.00,0.06,2
25,795024.00,0.06,421015.00,0.06,374009.00,0.06,2021,California,3,395789.00,0.03,140447.00,0.02,255342.00,0.04,3
26,2274180.00,0.17,895404.00,0.12,1378776.00,0.23,2021,California,4,428857.00,0.03,155752.00,0.02,273105.00,0.05,4
27,2307994.00,0.17,934791.00,0.13,1373203.00,0.23,2021,California,5,882663.00,0.07,343803.00,0.05,538860.00,0.09,5
28,1825351.00,0.14,900633.00,0.12,924718.00,0.16,2021,California,6,1239134.00,0.09,531604.00,0.07,707530.00,0.12,6
29,1268311.00,0.10,767569.00,0.10,500742.00,0.09,2021,California,7,1947417.00,0.15,938296.00,0.13,1009121.00,0.17,7
30,2484952.00,0.19,1889661.00,0.26,595291.00,0.10,2021,California,8,1621793.00,0.12,896086.00,0.12,725707.00,0.12,8
31,184511.00,0.01,0.00,0.00,184511.00,0.03,2021,California,9,2310752.00,0.17,1478550.00,0.20,832202.00,0.14,9
32,1791.00,17.91,1943.00,19.43,1698.00,16.98,2021,California,10,3311027.00,0.25,2516954.00,0.34,794073.00,0.14,10
33,523817.00,0.05,443518.00,0.07,80299.00,0.02,2021,Texas,0,321026.00,0.03,121766.00,0.02,199260.00,0.05,0
34,886569.00,0.09,768140.00,0.12,118429.00,0.03,2021,Texas,1,261778.00,0.03,91950.00,0.01,169828.00,0.04,1
35,1488015.00,0.14,994817.00,0.16,493198.00,0.13,2021,Texas,2,381790.00,0.04,158169.00,0.03,223621.00,0.06,2
36,1200447.00,0.12,540910.00,0.09,659537.00,0.17,2021,Texas,3,380507.00,0.04,166521.00,0.03,213986.00,0.06,3
37,2607562.00,0.26,1199749.00,0.19,1407813.00,0.37,2021,Texas,4,413003.00,0.04,184101.00,0.03,228902.00,0.06,4
38,1602456.00,0.16,986293.00,0.15,616163.00,0.16,2021,Texas,5,870908.00,0.09,405983.00,0.06,464925.00,0.12,5
39,799437.00,0.08,603296.00,0.09,196141.00,0.05,2021,Texas,6,1201280.00,0.12,610136.00,0.10,591144.00,0.15,6
40,396866.00,0.04,346272.00,0.05,50594.00,0.01,2021,Texas,7,1767665.00,0.17,1022954.00,0.16,744711.00,0.19,7
41,553351.00,0.05,508066.00,0.08,45285.00,0.01,2021,Texas,8,1297103.00,0.13,878896.00,0.14,418207.00,0.11,8
42,180821.00,0.02,0.00,0.00,180821.00,0.05,2021,Texas,9,1661203.00,0.16,1278904.00,0.20,382299.00,0.10,9
43,1161.00,11.61,1181.00,11.81,1146.00,11.46,2021,Texas,10,1683078.00,0.16,1471681.00,0.23,211397.00,0.06,10

### Cleaning Population

Firstly here, we will clean the population dataset, then merge it with both cleaned dataframes, `Household Income` and `Housing Cost` by renaming the `NAME` column in `df_pop_est` to `State` for consistency, reshaping the population dataset to have one row per state per year, and converting the `Year` column to just the year as an integer.

In [98]:
# Renaming the NAME column in df_pop_est to State for consistency
df_pop_est.rename(columns={"NAME": "State"}, inplace=True)

# Reshape the population dataset to have one row per state per year
df_pop_est_melted = df_pop_est.melt(id_vars='State', value_vars=["POPESTIMATE2020", "POPESTIMATE2021"], var_name='Year', value_name='Population')

# Convert the 'Year' column to just the year as an integer
df_pop_est_melted['Year'] = df_pop_est_melted['Year'].str.replace('POPESTIMATE','').astype(int)

# Now merge the dataframes on both 'State' and 'Year'
df = pd.merge(df, df_pop_est_melted, on=["State", "Year"], how="inner")
df.head()

,Housing Occupied housing units,Housing Percent occupied housing units,Housing Owner-occupied housing units,Housing Percent owner-occupied housing units,Housing Renter-occupied housing units,Housing Percent renter-occupied housing units,Year,State,Housing Cost Index,Income Occupied housing units,Income Percent occupied housing units,Income Owner-occupied housing units,Income Percent owner-occupied housing units,Income Renter-occupied housing units,Income Percent renter-occupied housing units,Income Income Index,Population
0,390873.00,0.03,274063.00,0.04,116810.00,0.02,2020,California,0,365131.00,0.03,123955.00,0.02,241176.00,0.04,0,39501653
1,682136.00,0.05,535640.00,0.07,146496.00,0.03,2020,California,1,249756.00,0.02,77011.00,0.01,172745.00,0.03,1,39501653
2,1164232.00,0.09,799003.00,0.11,365229.00,0.06,2020,California,2,507398.00,0.04,141153.00,0.02,366245.00,0.06,2,39501653
3,879823.00,0.07,418214.00,0.06,461609.00,0.08,2020,California,3,435382.00,0.03,152387.00,0.02,282995.00,0.05,3,39501653
4,2431992.00,0.19,914962.00,0.13,1517030.00,0.26,2020,California,4,474093.00,0.04,171950.00,0.02,302143.00,0.05,4,39501653

Now, we need to clean the combination dataframe by creating a dictionary for the income and housing costs and replacing the `Income Income Index` and `Housing Cost Index` columns with `income_mapping` and `housing_cost_mapping` before dropping the duplicate columns. After that, we also format data for further analysis and decision-making as previous steps.

In [99]:
# Clean df
df_clean = df.copy()

# Create a dictionary for the income and housing costs
income_mapping = household_income_ref.set_index('Income Index')['Household Income'].to_dict()
housing_cost_mapping = housing_cost_ref.set_index('Cost Index')['Housing Cost'].to_dict()

# Replace the Income Income Index and Housing Cost Index columns in the
df_clean['Income Category'] = df_clean['Income Income Index'].replace(income_mapping)
df_clean['Housing Cost Category'] = df_clean['Housing Cost Index'].replace(housing_cost_mapping)

# Drop the duplicate columns
df_clean = df_clean.drop(columns=['Income Income Index', 'Housing Cost Index'])

# Formatting data
# Replace "to" with "-"
df_clean['Housing Cost Category'] = df_clean['Housing Cost Category'].str.replace('to', '-')
df_clean['Housing Cost Category'] = df_clean['Housing Cost Category'].str.replace('to', '-')
df_clean['Income Category'] = df_clean['Income Category'].str.replace('to', '-')
df_clean['Income Category'] = df_clean['Income Category'].str.replace('to', '-')

# Remove all "$"
df_clean['Housing Cost Category'] = df_clean['Housing Cost Category'].str.replace('$', '', regex=False)
df_clean['Housing Cost Category'] = df_clean['Housing Cost Category'].str.replace('(dollars)', '', regex=False)
df_clean['Income Category'] = df_clean['Income Category'].str.replace('$', '', regex=False)
df_clean['Income Category'] = df_clean['Income Category'].str.replace('(dollars)', '', regex=False)

# Replace "Less than" and "or more" 
df_clean['Housing Cost Category'] = df_clean['Housing Cost Category'].str.replace('Less than', '<')
df_clean['Housing Cost Category'] = df_clean['Housing Cost Category'].str.replace('3,000 or more', '≥ 3000')
df_clean['Income Category']  = df_clean['Income Category'].str.replace('Less than', '<')
df_clean['Income Category']  = df_clean['Income Category'].str.replace('150,000 or more', '≥ 150,000')

df_clean.head(2)

,Housing Occupied housing units,Housing Percent occupied housing units,Housing Owner-occupied housing units,Housing Percent owner-occupied housing units,Housing Renter-occupied housing units,Housing Percent renter-occupied housing units,Year,State,Income Occupied housing units,Income Percent occupied housing units,Income Owner-occupied housing units,Income Percent owner-occupied housing units,Income Renter-occupied housing units,Income Percent renter-occupied housing units,Population,Income Category,Housing Cost Category
0,390873.00,0.03,274063.00,0.04,116810.00,0.02,2020,California,365131.00,0.03,123955.00,0.02,241176.00,0.04,39501653,"< 5,000",< 300
1,682136.00,0.05,535640.00,0.07,146496.00,0.03,2020,California,249756.00,0.02,77011.00,0.01,172745.00,0.03,39501653,"5,000 - 9,999",300 - 499